
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '../components/style/main.scss'
import { AuthProvider } from "./Providers";
import { Toaster } from "react-hot-toast";
import PageLoader from "@/components/loader/PageLoader";
// import Footer from "@/components/common/footer/Footer";
// import Header from "@/components/common/Header/Headercomp";
import ReduxProvider from "@/redux/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bindu Jewellery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <ReduxProvider>

         <Toaster position="top-right" />

            <PageLoader />
        {children}
            </ReduxProvider>
        
        </body>
      </AuthProvider>
    </html>
  );
}
